# Single-module build: everything links into acer_kbd_backlight.ko.
obj-m += acer_kbd_backlight.o
acer_kbd_backlight-objs += acer_kbd_core.o acer_kbd_wmi.o
acer_kbd_backlight-objs += acer_kbd_clevo.o acer_kbd_led.o

ccflags-y += -Wall -Wextra -Werror=implicit-function-declaration
